### ISSUE TITLE
I can't figure out how to inherit variables from higher level sections

### ISSUE THREAD

**Issue by timjstewart** [zweifisch/ob-http#23]
Hi,

This is more of a documentation issue than anything else.

I am using ob-http to make multiple, different REST calls and many of the RESTful POST calls have similar JSON values in the posted payload.  I was hoping to define HEADERS for each of those common values and put those HEADER definitions in a higher level section such that lower level sections would inherit them.  That way, if they change, I can change them in one place.  I have tried dozens of formats and nothing has worked yet.  

Here is what I'd like to be able to do:

```
* Deploy My Infrastructure
#+HEADER:   :var  network='network01'
#+HEADER:   :var  environment='dev'
#+HEADER:   :var  region='south'

** Deploy Mongo

#+BEGIN_SRC http
POST http://my-deployer.com/deploy
{
   "type": "mongodb", 
   "network": "${network}",        // <- Goal: Inherit this from higher level section
   "region": "${region}",
   "environment": "${environment}",
   ... other settings specific to MongoDB
}
#+END_SRC

** Deploy Redis

#+BEGIN_SRC http
POST http://my-deployer.com/deploy

{ 
   "type": "redisdb",
   "network": "${network}",
   "region": "${region}",
   "environment": "${environment}",
   ... other settings specific to Redis
}
#+END_SRC
```

Is there a way to do this?  Thanks!!

**Comment by timjstewart** [comment]
I forgot to mention the most important part.  I also want to define HEADERs at lower section levels too and have those lower level HEADERs merged with the higher level HEADERS.

UPDATE: It appears that I was using tick marks instead of double quotes and that has improved my results, but I still can't seem to get HEADERS defined at different levels to merge.

**Comment by timjstewart** [comment]
Here is the syntax that appears to solve my first problem (but not the property merging problem).

```
* Deploy My Infrastructure
   :PROPERTIES:
   :var:      network="network01" environment="dev" region="south"
   :END:
```

**Comment by zweifisch** [comment]
@timjstewart Sorry for the late response. You can append variables in subtrees using `var+`

```
:properties:
:var+: more="value"
:end:
```

**Comment by finalclass** [comment]
Is the syntax still working? For me it seams that it's not.
