### ISSUE TITLE
Export does not substitute variables

### ISSUE THREAD

**Issue by nodo** [zweifisch/ob-http#25]
Hello,

I have an issue when exporting a org document using `ob-http`.  I am using variables at the beginning of the file to store common information about the requests. However, when exporting, these variables are not substituted.

For instance, given the following document:
```
:PROPERTIES:
:var: url="https://api.github.com/repos/zweifisch/ob-http/languages"
:END:

A simple request:
#+BEGIN_SRC http :pretty
GET ${url}
#+END_SRC

#+RESULTS:
: {
:   "Emacs Lisp": 13933,
:   "Shell": 139
: }
```

When exporting to ASCII produces something like:
```
A simple request:
,----
| GET ${url}
`----
```

Instead, I would expect something like:
```
A simple request:
,----
| GET https://api.github.com/repos/zweifisch/ob-http/languages
`----
```

Please, can you help me with that? If needed, I would be happy to help implementing this.

Thanks!

**Comment by zweifisch** [comment]
@nodo Pull requests are welcome :laughing:

**Comment by nodo** [comment]
Looks like this is fixed 🎉 , should we close the issue? @zweifisch
