### ISSUE TITLE
Properties example does not work

### ISSUE THREAD

**Issue by jsab** [zweifisch/ob-http#27]
I'm trying to use the following example taken from README.org

```` org
* api test
:PROPERTIES:
:var: token="secret"
:host: httpbin.org
:pretty: json
:END:

#+BEGIN_SRC http
POST /post
Content-Type: application/json
X-Auth-Token: ${token}
#+END_SRC
````

However, when I execute the code block, I get the following message:

`Cannot resolve a template to values`

I'm using:
`  ob-http            20170218.503`
`  org                20170210`

**Comment by zweifisch** [comment]
It's a breaking change in org-mode. Just updated the example.
```
:PROPERTIES:
:header-args: :var token="secret" :host httpbin.org :pretty
:END:
```

**Comment by jsab** [comment]
This issue is resolved.
