### ISSUE TITLE
Add ability to get all headers

### ISSUE THREAD

**Issue by robbyoconnor** [zweifisch/ob-http#36]
I have a use-case where I need to be able to look at **_ALL_** headers...so it'd be useful to be able to get those...even the raw output would be nice similar to `curl -v`

**Comment by zweifisch** [comment]
Hard to achieve with ob-http, you could just use `sh`
```
#+BEGIN_SRC sh
curl -v URL
#+END_SRC
```

**Comment by ewestbrook** [comment]
Using `:pretty no` works for me.

```
#+BEGIN_SRC http :pretty no
GET http://localhost/
#+END_SRC
```
