### ISSUE TITLE
Is there any way to get the http status code?

### ISSUE THREAD

**Issue by haditim** [zweifisch/ob-http#47]
Hello and thanks for the amazing project.
I do not seem to be able to get the HTTP status code from the request in the results. Am I missing something? I use it this way:

```
#+BEGIN_SRC http :pretty :var auth_token=token_req :var uuid=storage
GET /storage/${uuid}
content-Type: application/json
Authorization: Bearer ${auth_token}

#+END_SRC

#+RESULTS:
#+begin_example
[
  {
    "id": "becb15e1-e70a-43ed-946e-90551a1eadf4",
    "name": "test from Hadi",
    "projects": [
      "7f3d3f48-74f3-40b1-872e-475814b4173e"
    ],
  }
]
#+end_example
```

**Comment by davidshen84** [comment]
Remove the `:pretty` option and it will return the HTTP headers in the buffer.

**Comment by nfedyashev** [comment]
@haditim I suggest closing this issue because David explained it. 
WDYT?

**Comment by haditim** [comment]
> @haditim I suggest closing this issue because David explained it. WDYT?

Sure, apologies for forgetting to close the issue.
