### ISSUE TITLE
aget is deprecated, throws compiler warnings as a missing symbol

### ISSUE THREAD

**Issue by dgtized** [zweifisch/ob-http#7]
On Emacs 25 preview I'm getting the following compiler warning:

```
In end of data:
ob-http.el:193:1:Warning: the function ‘aget’ is not known to be defined.
```

I investigated and aget is defined in assoc.el which is marked as obsolete.

**Comment by zweifisch** [comment]
Yeah, already fixed thanks to @syohex . Thanks for the detailed bug report!
