### ISSUE TITLE
the #+HEADER vars not working 

### ISSUE THREAD

**Issue by eggcaker** [zweifisch/ob-http#9]
it not working if define the vars from `#+HEADER:  var name="ob-htt"`. some error : 

```
Wrong number of arguments: #[(key alist) "ÂÃ!	\"" [key alist assoc-default intern] 3], 1
```

I guess problem is ob-http cant read the Headers vars. it works with 
`#+BEGIN_SRC http :select .json:var name="ob-http"`.

**Comment by eggcaker** [comment]
OK , found why it happen. should be define the vars with syntax 

```
#+PROPERTY: header-args :var name="ob-http"
```

you should update the read me though.

**Comment by zweifisch** [comment]
Hi, looks like the semicolon before `var` is missing, should be `#+HEADER: :var foo="bar" f="b"`
